<?php

return ['lang' => array(

	'NextActionsTitle' => 'Next Actions',
	'WaitingForsTitle' => 'Waiting Fors',

	// Weekly Review

	'WeeklyReviewTitle' => 'Weekly Review',

	'GetClearSubtitle' => 'Get Clear',
	'CollectLoosePapers' => 'Collect loose papers and materials',
	'CollectLoosePapersDetails' => 'Gather all accumulater business cards, receipts, and miscellaneous paper-based materials into your in-basket.',
	'GetInZero' => 'Get "IN" to zero',
	'GetInZeroDetails' => 'Process completely all outstanding paper materials, journal and meeting notes, voicemail, dictation, and e-mails.',
	'EmptyHead' => 'Empty your head',
	'EmptyHeadDetails' => 'Put in writing any process and uncaptured new projects, action items, waiting-for\'s, someday-maybe\'s, etc.',
	
	'GetCurrentSubtitle' => 'Get Current',
	'ReviewActions' => 'Review Action Lists',
	'ReviewActionsDetails' => 'Mark off completed actions. Review for reminders of further action steps to record.',
	'ReviewPrevCalendar' => 'Review Previous Calendar Data',
	'ReviewPrevCalendarDetails' => 'Review past calendar in detail for remaining action items, reference data, etc. and transfer into the active system.',
	'ReviewUpcomingCalendar' => 'Review Upcoming Calendar',
	'ReviewUpcomingCalendarDetails' => 'Review upcoming calendar events - long and short term. Capture actions triggered.',
	'ReviewWaitingFors' => 'Review Waiting-For List',
	'ReviewWaitingForsDetails' => 'Record appropriate actions for any needed follow-up. Check off received ones.',
	'ReviewProjects' => 'Review Project (and Larger Outcome) Lists',
	'ReviewProjectsDetails' => 'Evaluate status of projects, goals and outcomes, one by one, ensuring at least one current action item on each. Browse through work-in-progress support material to trigger new actions, completions, waiting-for\'s, etc.',
	'ReviewChecklists' => 'Review Any Relevant Checklists',
	'ReviewChecklistsDetails' => 'Use as a trigger for any new actions.',

	'GetCreativeSubtitle' => 'Get Creative',
	'ReviewSomeday' => 'Review Someday/Maybe List',
	'ReviewSomedayDetails' => 'Review for any projects which may now have become active, and transfer to "Projects." Delete items no longer of interest.',
	'BeCreative' => 'Be Creative & Courageous',
	'BeCreativeDetails' => 'Any new, wonderful, hare-brained, creative, thought-provoking, risk-taking ideas to add into your system???',

	'InboxItemsNumber' => '{0,number} Inbox Item(s) need processing',
	'ActionsPastDueNumber' => '{0,number} Actions(s) are past due date',
	'WaitingForsPastDueNumber' => '{0,number} Waiting For(s) are past due date',
	'ProjectsNoOutcomesNumber' => '{0,number} Project(s) are missing outcomes',
	'ProjectsNoNextActionsNumber' => '{0,number} Project(s) have no Next Action defined',
	
	// Item Fields

	'ItemTitleLabel' => 'Title',
	'ItemDescriptionLabel' => 'Description',
	'ItemCategoryLabel' => 'Category',
	'ItemParentLabel' => 'Parents',
	'ItemOutcomeLabel' => 'Outcome',
	'ItemOutcomeTip' => 'What will have happened when this can be checked off?',
	'ItemTickleDateLabel' => 'Tickle Date',
	'ItemDeadlineLabel' => 'Deadline',
	'ItemRepeatsLabel' => 'Repeats',
	'ItemNextActionLabel' => 'Next Action',
	'ItemSpaceContextLabel' => 'Space Context',
	'ItemTimeContextLabel' => 'Time Context',
	
	'CreateButton' => 'Create',
	'CreateAndProcessInboxButton' => 'Create and Process Inbox',
	'CreateAndNextActionButton' => 'Create and add Next Action',
	'CreateAndWaitingForButton' => 'Create and add Waiting For',
	
	'ProjectTitleLabel' => 'Project Title',
	'ProjectOutcomeLabel' => 'Project Outcome',
	'SomedayMaybeLabel' => 'Someday/Maybe',
	'ProjectDescriptionLabel' => 'Project Description',
	'ProjectDeadlineLabel' => 'Project Deadline',
	'ProjectCategoryLabel' => 'Project Category',
	'ListItemsLabel' => 'List Items',

	'RepetsNever' => 'Doesn\'t Repeat',
	'RepeatsDaily' => 'Daily',
	'RepeatsWeekly' => 'Weekly',
	'RepeatsMonthly' => 'Monthly',
	'RepeatsYearly' => 'Yearly',
	'RepeatEvery'  => 'Repeat every',
	'RepeatsOn' => 'Repeats on',
	'Days' => 'days',
	'Weeks' => 'weeks',
	'Months' => 'months',
	'Years' => 'years',
	'Ends' => 'Ends',
	'Never' => 'never',
	'Until' => 'until',
	'DayOfMonth' => 'day of month',
	'DayOfWeek' => 'day of week',

	'Mon' => 'Mon',
	'Tue' => 'Tue',
	'Wed' => 'Wed',
	'Thu' => 'Thu',
	'Fri' => 'Fri',
	'Sat' => 'Sat',
	'Sun' => 'Sun',
	
	'InboxNotificationLabel' => 'Inbox',
	'InboxNotificationTitle' => 'Process Inbox',
	'AddInboxMenuItem' => '<span class="key-short">i</span>nbox',
	'AddActionMenuItem' => '<span class="key-short">a</span>ction',
	'AddProjectMenuItem' => '<span class="key-short">p</span>roject',
	'AddWaitingForMenuItem' => '<span class="key-short">w</span>aiting for',
	'ProcessInboxTitle' => 'Process Inbox',
	'EditReferenceTitle' => 'Edit Reference',
	'EditListTitle' => 'Edit List',
	'EditChecklistTitle' => 'Edit Checklist',
	'EditProjectTitle' => 'Edit Project',
	'EditActionTitle' => 'Edit Action',
	'EditWaitingForTitle' => 'Edit Waiting For',
	'FieldEmpty' => '(Field Empty)',
	'IsActionableQuestion' => 'What is it? Is it actionable?',
	'InboxEmptyMsg' => 'The Inbox is empty.',

	'No' => 'No',
	'Yes' => 'Yes',

	'ItemType_m' => 'Life',
	'ItemType_v' => '3-5 Year Goal',
	'ItemType_o' => '1-2 Year Goal',
	'ItemType_g' => 'Area of Focus',
	'ItemType_a' => 'Action',
	'ItemType_i' => 'Inbox Item',
	'ItemType_p' => 'Project',
	'ItemType_w' => 'Waiting For',
	'ItemType_r' => 'Reference',
	'ItemType_L' => 'List',
	'ItemType_C' => 'Checklist',
	'ItemType_T' => 'List Item',

	'DeleteButtonLabel' => '<span class="key-short">D</span>elete',
	'ReferenceButtonLabel' => '<span class="key-short">R</span>eference',
	'ListButtonLabel' => '<span class="key-short">L</span>ist',
	'ChecklistButtonLabel' => 'Chec<span class="key-short">k</span>list',
	'ListItemButtonLabel' => 'List <span class="key-short">i</span>tem',
	'CompleteButtonLabel' => '<span class="key-short">C</span>omplete',
	'ActionButtonLabel' => '<span class="key-short">A</span>ction',
	'WaitingForButtonLabel' => '<span class="key-short">W</span>aiting For',
	'ProjectButtonLabel' => '<span class="key-short">P</span>roject'

)];
