<?php

return ['lang' => array(

	'NextActionsTitle' => 'Next Actions',
	'WaitingForsTitle' => 'Waiting Fors',
	
	'ItemTitleLabel' => 'Title',
	'ItemDescriptionLabel' => 'Description',
	'ItemCategoryLabel' => 'Category',
	'ItemParentLabel' => 'Parents',
	'ItemOutcomeLabel' => 'Outcome',
	'ItemOutcomeTip' => 'What will have happened when this can be checked off?',
	'ItemTickleDateLabel' => 'Tickle Date',
	'ItemDeadlineLabel' => 'Deadline',
	'ItemRepeatsLabel' => 'Repeats',
	'ItemNextActionLabel' => 'Next Action',
	'ItemSpaceContextLabel' => 'Space Context',
	'ItemTimeContextLabel' => 'Time Context',
	
	'CreateButton' => 'Create',
	'CreateAndProcessInboxButton' => 'Create and Process Inbox',
	'CreateAndNextActionButton' => 'Create and add Next Action',
	'CreateAndWaitingForButton' => 'Create and add Waiting For',
	
	'ProjectTitleLabel' => 'Project Title',
	'ProjectOutcomeLabel' => 'Project Outcome',
	'SomedayMaybeLabel' => 'Someday/Maybe',
	'ProjectDescriptionLabel' => 'Project Description',
	'ProjectDeadlineLabel' => 'Project Deadline',
	'ProjectCategoryLabel' => 'Project Category',
	'ListItemsLabel' => 'List Items',

	'RepetsNever' => 'Doesn\'t Repeat',
	'RepeatsDaily' => 'Daily',
	'RepeatsWeekly' => 'Weekly',
	'RepeatsMonthly' => 'Monthly',
	'RepeatsYearly' => 'Yearly',
	'RepeatEvery'  => 'Repeat every',
	'RepeatsOn' => 'Repeats on',
	'Days' => 'days',
	'Weeks' => 'weeks',
	'Months' => 'months',
	'Years' => 'years',
	'Ends' => 'Ends',
	'Never' => 'never',
	'Until' => 'until',
	'DayOfMonth' => 'day of month',
	'DayOfWeek' => 'day of week',
	
	'InboxNotificationLabel' => 'Inbox',
	'InboxNotificationTitle' => 'Process Inbox',
	'AddInboxMenuItem' => '<span class="key-short">i</span>nbox',
	'AddActionMenuItem' => '<span class="key-short">a</span>ction',
	'AddProjectMenuItem' => '<span class="key-short">p</span>roject',
	'AddWaitingForMenuItem' => '<span class="key-short">w</span>aiting for',
	'ProcessInboxTitle' => 'Process Inbox',
	'EditReferenceTitle' => 'Edit Reference',
	'EditListTitle' => 'Edit List',
	'EditChecklistTitle' => 'Edit Checklist',
	'EditProjectTitle' => 'Edit Project',
	'EditActionTitle' => 'Edit Action',
	'EditWaitingForTitle' => 'Edit Waiting For',
	'FieldEmpty' => '(Field Empty)',
	'IsActionableQuestion' => 'What is it? Is it actionable?',
	'InboxEmptyMsg' => 'The Inbox is empty.',

	'No' => 'No',
	'Yes' => 'Yes',

	'ItemType_m' => 'Life',
	'ItemType_v' => '3-5 Year Goal',
	'ItemType_o' => '1-2 Year Goal',
	'ItemType_g' => 'Area of Focus',
	'ItemType_a' => 'Action',
	'ItemType_i' => 'Inbox Item',
	'ItemType_p' => 'Project',
	'ItemType_w' => 'Waiting For',
	'ItemType_r' => 'Reference',
	'ItemType_L' => 'List',
	'ItemType_C' => 'Checklist',
	'ItemType_T' => 'List Item',

	'DeleteButtonLabel' => '<span class="key-short">D</span>elete',
	'ReferenceButtonLabel' => '<span class="key-short">R</span>eference',
	'ListButtonLabel' => '<span class="key-short">L</span>ist',
	'ChecklistButtonLabel' => 'Chec<span class="key-short">k</span>list',
	'ListItemButtonLabel' => 'List <span class="key-short">i</span>tem',
	'CompleteButtonLabel' => '<span class="key-short">C</span>omplete',
	'ActionButtonLabel' => '<span class="key-short">A</span>ction',
	'WaitingForButtonLabel' => '<span class="key-short">W</span>aiting For',
	'ProjectButtonLabel' => '<span class="key-short">P</span>roject'

)];
